version: '3.8'

services:
  # Redis for caching and sessions (still needed)
  redis:
    image: redis:7-alpine
    container_name: hireiq-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hireiq-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django Backend (connects to MongoDB Atlas)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hireiq-backend
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_NAME=${MONGODB_NAME:-hireiq_db}
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@redis:6379/0
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_OAUTH2_KEY=${GOOGLE_OAUTH2_KEY}
      - GOOGLE_OAUTH2_SECRET=${GOOGLE_OAUTH2_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-True}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DJANGO_SETTINGS_MODULE=hireiq_backend.settings_production
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/app/media
      - ./backend/static:/app/static
      - ./backend/logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hireiq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${FRONTEND_API_URL:-http://localhost:8000/api}
        - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    container_name: hireiq-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hireiq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: hireiq-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./backend/static:/var/www/static:ro
      - ./backend/media:/var/www/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - hireiq-network
    profiles:
      - production

volumes:
  redis_data:
    driver: local

networks:
  hireiq-network:
    driver: bridge